// SPDX-FileCopyrightText: 2026 WhaTalker Inc.
// SPDX-License-Identifier: AGPL-3.0-only

//! Corulix 1.1.0 (ADR 0012, Phase I): pure, side-effect-free rendering for
//! `corulix instructions generate`. This module performs no filesystem I/O
//! -- `wht_corulix_cli::main::run_instructions_generate` owns the actual
//! managed-write logic, using `wht_corulix_workspace`'s existing pinned
//! create/rename primitives (the same ones `wht_corulix_mutation` uses for
//! governed edits) to write what this module renders.
//!
//! Generated content is advisory documentation (Architecture: this crate's
//! own `capability_notes.rs` anti-coaching discipline applies here too --
//! see [`render_agents_body`]) and is never itself deserialized back into
//! runtime security authority by any Corulix code path.

use wht_corulix_core::{CANONICAL_MCP_TOOL_NAMES, ContentHash, EffectiveToolSet};

/// The literal, greppable marker every Corulix-generated managed file
/// starts with. [`is_corulix_managed`] is the sole authority for deciding
/// whether an existing file may be safely replaced by a fresh `--write` --
/// never a heuristic on file extension, mtime, or size.
pub const MANAGED_MARKER_PREFIX: &str = "<!-- CORULIX-MANAGED:";

/// Corulix 1.1.0 (ADR 0012): `corulix instructions generate --format`'s
/// two supported output shapes. There is no standalone Claude mode in
/// 1.1.0 -- `Claude` emits only the one-line `@AGENTS.md` compatibility
/// bridge (current official Anthropic `CLAUDE.md` `@path` import support).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InstructionsFormat {
    Agents,
    Claude,
}

impl InstructionsFormat {
    #[must_use]
    pub const fn schema_tag(self) -> &'static str {
        match self {
            Self::Agents => "agents",
            Self::Claude => "claude",
        }
    }
}

/// Whether `content` begins with [`MANAGED_MARKER_PREFIX`] (leading
/// whitespace tolerated, byte-for-byte prefix match otherwise). This is the
/// **entire** "is this file ours to overwrite" authority -- a target that
/// exists but does not start with this exact marker is never touched by
/// `--write`, regardless of its apparent content.
#[must_use]
pub fn is_corulix_managed(content: &[u8]) -> bool {
    match std::str::from_utf8(content) {
        Ok(text) => text.trim_start().starts_with(MANAGED_MARKER_PREFIX),
        Err(_) => false,
    }
}

/// Renders the full contents of a Corulix-managed `AGENTS.md` (or its
/// `@AGENTS.md`-bridging `CLAUDE.md`) for `effective` -- the resolved
/// workspace's own effective MCP tool set. Deterministic: the same
/// `effective` value always renders byte-for-byte the same output, which
/// is what makes `--check` a meaningful, mutation-free drift comparison.
#[must_use]
pub fn render(format: InstructionsFormat, effective: &EffectiveToolSet) -> String {
    let body = match format {
        InstructionsFormat::Agents => render_agents_body(effective),
        InstructionsFormat::Claude => render_claude_bridge_body(),
    };
    let fingerprint = ContentHash::compute_sha256(body.as_bytes()).digest_hex;
    format!(
        "{MANAGED_MARKER_PREFIX} format={} schema=1 fingerprint={fingerprint} -->\n\n{body}",
        format.schema_tag()
    )
}

/// The `AGENTS.md` body: which of the 14 canonical tools this workspace's
/// own effective policy leaves visible, and which it does not. Lists tool
/// **names** only, never a hand-authored capability description -- this
/// crate's own `capability_notes.rs` descriptions are reviewed, tested
/// prose spliced directly into the live `tools/list` response; duplicating
/// them here (in a second, independently-maintained location) would be
/// exactly the kind of drift-prone second source of truth Architecture
/// Rule A/ADR 0012 exist to prevent. A caller that wants the real
/// descriptions already receives them from `tools/list` itself.
///
/// Never names a specific tool as "hidden"/"disabled for a reason" beyond
/// the bare fact that it is disabled -- no routing coaching, matching
/// `capability_notes.rs`'s own forbidden-phrase discipline.
fn render_agents_body(effective: &EffectiveToolSet) -> String {
    let mut enabled: Vec<&'static str> = CANONICAL_MCP_TOOL_NAMES
        .iter()
        .copied()
        .filter(|name| effective.is_enabled(name))
        .collect();
    enabled.sort_unstable();
    let mut disabled: Vec<&'static str> = effective.disabled_names().collect();
    disabled.sort_unstable();

    let mut out = String::new();
    out.push_str("# AGENTS.md (Corulix-generated)\n\n");
    out.push_str(
        "Generated by `corulix instructions generate` from this workspace's own effective \
         Corulix MCP configuration. This file is advisory only and carries no Corulix \
         enforcement weight. Do not hand-edit between regenerations: edits to a \
         Corulix-managed file (identified by its own leading marker) are safe to make but will \
         be silently replaced by the next `--write`.\n\n",
    );
    out.push_str(&format!(
        "## Effective Corulix MCP tools ({} of {})\n\n",
        enabled.len(),
        EffectiveToolSet::canonical_tool_count()
    ));
    for name in &enabled {
        out.push_str(&format!("- `{name}`\n"));
    }
    if !disabled.is_empty() {
        out.push_str(&format!(
            "\n## Disabled by workspace policy ({})\n\n",
            disabled.len()
        ));
        for name in &disabled {
            out.push_str(&format!("- `{name}`\n"));
        }
    }
    out
}

/// The `CLAUDE.md` body: exactly the one-line `@AGENTS.md` compatibility
/// import, per current official Anthropic `CLAUDE.md` documentation. No
/// standalone duplicated-content mode exists in Corulix 1.1.0.
fn render_claude_bridge_body() -> String {
    "@AGENTS.md\n".to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_is_deterministic_for_the_same_effective_set() {
        let a = render(InstructionsFormat::Agents, &EffectiveToolSet::all_enabled());
        let b = render(InstructionsFormat::Agents, &EffectiveToolSet::all_enabled());
        assert_eq!(a, b);
    }

    #[test]
    fn render_output_is_recognized_as_managed() {
        let rendered = render(InstructionsFormat::Agents, &EffectiveToolSet::all_enabled());
        assert!(is_corulix_managed(rendered.as_bytes()));
    }

    #[test]
    fn unmanaged_content_is_never_recognized_as_managed() {
        assert!(!is_corulix_managed(
            b"# Hand-authored AGENTS.md\n\nDo not touch.\n"
        ));
        assert!(!is_corulix_managed(b""));
    }

    #[test]
    fn all_enabled_lists_all_14_and_no_disabled_section() -> Result<(), String> {
        let rendered = render(InstructionsFormat::Agents, &EffectiveToolSet::all_enabled());
        assert!(rendered.contains("Effective Corulix MCP tools (14 of 14)"));
        assert!(!rendered.contains("Disabled by workspace policy"));
        for name in CANONICAL_MCP_TOOL_NAMES {
            assert!(
                rendered.contains(&format!("`{name}`")),
                "expected {name} to be listed as enabled"
            );
        }
        Ok(())
    }

    #[test]
    fn reduced_policy_lists_disabled_section_and_excludes_disabled_names()
    -> Result<(), Box<dyn std::error::Error>> {
        let policy = wht_corulix_core::validate_tool_policy(
            &["semantic".to_string(), "format_preview".to_string()],
            false,
        )?;
        let rendered = render(InstructionsFormat::Agents, &policy);
        assert!(rendered.contains("Effective Corulix MCP tools (12 of 14)"));
        assert!(rendered.contains("Disabled by workspace policy (2)"));
        assert!(rendered.contains("`semantic`"));
        assert!(rendered.contains("`format_preview`"));
        // The disabled-section listing is the only place a disabled name
        // may appear -- the enabled section must not double-list it.
        let enabled_section = rendered
            .split("## Disabled by workspace policy")
            .next()
            .unwrap_or_default();
        assert!(!enabled_section.contains("`semantic`"));
        assert!(!enabled_section.contains("`format_preview`"));
        Ok(())
    }

    #[test]
    fn claude_bridge_is_exactly_the_agents_import_line() {
        let rendered = render(InstructionsFormat::Claude, &EffectiveToolSet::all_enabled());
        assert!(rendered.ends_with("@AGENTS.md\n"));
        assert!(is_corulix_managed(rendered.as_bytes()));
    }

    #[test]
    fn no_forbidden_coaching_phrase_in_generated_output() {
        for format in [InstructionsFormat::Agents, InstructionsFormat::Claude] {
            let rendered = render(format, &EffectiveToolSet::all_enabled());
            let lower = rendered.to_lowercase();
            for phrase in ["prefer ", "fall back", "fallback to"] {
                assert!(
                    !lower.contains(phrase),
                    "generated {format:?} output contains a coaching phrase: {phrase:?}"
                );
            }
        }
    }
}
