# WhaTalker Corulix -- wht_corulix_index Crate Manifest
# Copyright (c) 2026 WhaTalker Inc.
# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "wht_corulix_index"
description = "Snapshot and index state for WhaTalker Corulix"
version = "1.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
license-file.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
publish = ["crates-io"]

[dependencies]
wht_corulix_core.workspace = true

[lints]
workspace = true
